// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"
	database "rena-server-v2/internal/item/database"

	mock "github.com/stretchr/testify/mock"

	model "rena-server-v2/internal/item/model"
)

// ItemDB is an autogenerated mock type for the ItemDB type
type ItemDB struct {
	mock.Mock
}

// DeleteItemBySlug provides a mock function with given fields: ctx, authorId, slug
func (_m *ItemDB) DeleteItemBySlug(ctx context.Context, authorId uint, slug string) error {
	ret := _m.Called(ctx, authorId, slug)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, authorId, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindItemBySlug provides a mock function with given fields: ctx, slug
func (_m *ItemDB) FindItemBySlug(ctx context.Context, slug string) (*model.Item, error) {
	ret := _m.Called(ctx, slug)

	var r0 *model.Item
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Item); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindItems provides a mock function with given fields: ctx, criteria
func (_m *ItemDB) FindItems(ctx context.Context, criteria database.IterateItemCriteria) ([]*model.Item, int64, error) {
	ret := _m.Called(ctx, criteria)

	var r0 []*model.Item
	if rf, ok := ret.Get(0).(func(context.Context, database.IterateItemCriteria) []*model.Item); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Item)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, database.IterateItemCriteria) int64); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, database.IterateItemCriteria) error); ok {
		r2 = rf(ctx, criteria)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RunInTx provides a mock function with given fields: ctx, f
func (_m *ItemDB) RunInTx(ctx context.Context, f func(context.Context) error) error {
	ret := _m.Called(ctx, f)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveItem provides a mock function with given fields: ctx, item
func (_m *ItemDB) SaveItem(ctx context.Context, item *model.Item) error {
	ret := _m.Called(ctx, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Item) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
